### ISSUE TITLE
Scheduled toots are publicly accessible

### ISSUE THREAD

**Issue by ldjb** [DavidLibeau/mastodon-scheduler#1]
I'm not sure whether this is intended behaviour or not, but it's possible to access other people's scheduled toots.

For example, you can view this one I made without even logging in:
http://scheduler.mastodon.tools/status/8

It's fairly easy to simply replace the status ID with some other number to access other toots.

Note that toots that have already been sent out are apparently deleted, so you can only access scheduled toots that have not yet been sent out.

Might I propose only allowing access to toots from the person who scheduled that toot?

Otherwise, if this is intended behaviour, the user should probably be informed of this before scheduling the toot.

It's just… some people might post sensitive information in these toots and don't want them released until a certain time.

Very useful tool, otherwise! :-)

EDIT: Looks like this is intended behaviour:
https://github.com/DavidLibeau/mastodon-scheduler/blob/d927b5509a954f93d4413d357fec633af988db66/src/AppBundle/Controller/statusController.php#L113

In which case I think users should be informed about this. Thoughts?

**Comment by DavidLibeau** [comment]
Thanks for the report.
For now, the toots are publics or will be published publicly. So you can see them with the status/show view.

I will change that in future releases !

**Comment by DavidLibeau** [comment]
Done ! 😄
